FROM public.ecr.aws/lambda/python:latest

WORKDIR ${LAMBDA_TASK_ROOT}

COPY requirements.txt .

RUN pip install -r requirements.txt 

COPY sns_fetch_games.py .

CMD ["sns_fetch_games.lambda_handler"]

