name: Pytest Workflow

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
  workflow_dispatch:

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v3

      - name: Set up Python 3.11
        uses: actions/setup-python@v1
        with:
          python-version: '3.11'

      - name: Run Pytest if Tests Exist
        run: |
          cd pipeline
          if find . -name "test_*.py" | grep .; then
            echo "Test files found. Running pytest..."
            pip install -r requirements.txt
            pytest . --maxfail=1
          else
            echo "No test files found. Skipping pytest."
          fi